# Generated by Django 2.2.1 on 2019-05-16 06:30

import OeBVServices.utilities.sluggenerator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_nr', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=OeBVServices.utilities.sluggenerator.create_random_slug, max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('shortname', models.CharField(blank=True, max_length=16, null=True)),
                ('club_admin', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['club_nr'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('oebv_nr', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=OeBVServices.utilities.sluggenerator.create_random_slug, max_length=16, unique=True)),
                ('last_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('master_points', models.PositiveIntegerField(default=0)),
                ('rank', models.CharField(choices=[('GM', 'Grandmaster'), ('JGM', 'Junior Grandmaster'), ('SLM', 'Senior Lifemaster'), ('LM', 'Lifemaster'), ('P', 'Pik'), ('H', 'Herz'), ('K', 'Karo'), ('T', 'Treff'), ('A', 'Anfänger')], default='A', max_length=3)),
                ('oebv_member', models.BooleanField(default=True)),
                ('club', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubmembers', to='OeBVAdmin.Club')),
                ('reg_user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'oebv_nr'],
            },
        ),
    ]
