# Generated by Django 2.2.1 on 2019-05-16 06:31

import OeBVServices.utilities.sluggenerator
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OeBVAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('tourn_type', models.CharField(choices=[('P', 'Paarturnier'), ('T', 'Teamturnier'), ('I', 'Individualturnier')], default='P', max_length=1)),
                ('registration_open', models.BooleanField(default=True)),
                ('slug', models.SlugField(default=OeBVServices.utilities.sluggenerator.create_random_slug, max_length=16, unique=True)),
                ('info', models.URLField(blank=True, null=True)),
                ('max_team_members', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(8)])),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='OeBVAdmin.Club')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
